/**
 * Party Management Micro Service V1
 * This service is the party manager
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.interop.selfcare.partymanagement.client.model

import it.pagopa.interop.selfcare.partymanagement.client.invoker.ApiModel




            sealed trait PartyRole extends ApiModel

            object PartyRole {

                    case object MANAGER extends PartyRole
                    case object DELEGATE extends PartyRole
                    case object SUB_DELEGATE extends PartyRole
                    case object OPERATOR extends PartyRole

            def fromValue(value: String): Either[Throwable, PartyRole] =
            value match {
                    case "MANAGER" => Right(MANAGER)
                    case "DELEGATE" => Right(DELEGATE)
                    case "SUB_DELEGATE" => Right(SUB_DELEGATE)
                    case "OPERATOR" => Right(OPERATOR)
            case other => Left(new RuntimeException(s"Unable to decode value $other"))
            }
            }

