/**
 * Party Management Micro Service V1
 * This service is the party manager
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.interop.selfcare.partymanagement.client.model

import it.pagopa.interop.selfcare.partymanagement.client.invoker.ApiModel




            sealed trait RelationshipState extends ApiModel

            object RelationshipState {

                    case object PENDING extends RelationshipState
                    case object ACTIVE extends RelationshipState
                    case object SUSPENDED extends RelationshipState
                    case object DELETED extends RelationshipState
                    case object REJECTED extends RelationshipState

            def fromValue(value: String): Either[Throwable, RelationshipState] =
            value match {
                    case "PENDING" => Right(PENDING)
                    case "ACTIVE" => Right(ACTIVE)
                    case "SUSPENDED" => Right(SUSPENDED)
                    case "DELETED" => Right(DELETED)
                    case "REJECTED" => Right(REJECTED)
            case other => Left(new RuntimeException(s"Unable to decode value $other"))
            }
            }

