/**
 * pdv-ms-user-registry
 * User Registry API documentation
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.interop.selfcare.userregistry.client.model

import it.pagopa.interop.selfcare.userregistry.client.invoker.ApiModel


            case class CertifiableFieldResourceOfstring (
                    /* Certified source of information */
                certification: CertifiableFieldResourceOfstringEnums.Certification,
                    /* Field value */
                value: String
            ) extends ApiModel

                object CertifiableFieldResourceOfstringEnums {

                        type Certification = Certification.Value
                        object Certification extends Enumeration {
                            val NONE = Value("NONE")
                            val SPID = Value("SPID")
                        }

                }


