/**
 * pdv-ms-user-registry
 * User Registry API documentation
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.interop.selfcare.userregistry.client.model

import it.pagopa.interop.selfcare.userregistry.client.invoker.ApiModel




            sealed trait Field extends ApiModel

            object Field {

                    case object birthDate extends Field
                    case object email extends Field
                    case object familyName extends Field
                    case object fiscalCode extends Field
                    case object name extends Field
                    case object workContacts extends Field

            def fromValue(value: String): Either[Throwable, Field] =
            value match {
                    case "birthDate" => Right(birthDate)
                    case "email" => Right(email)
                    case "familyName" => Right(familyName)
                    case "fiscalCode" => Right(fiscalCode)
                    case "name" => Right(name)
                    case "workContacts" => Right(workContacts)
            case other => Left(new RuntimeException(s"Unable to decode value $other"))
            }
            }

