/**
 * pdv-ms-user-registry
 * User Registry API documentation
 *
 * The version of the OpenAPI document: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.interop.selfcare.userregistry.client.model

    import java.util.UUID
import it.pagopa.interop.selfcare.userregistry.client.invoker.ApiModel


            case class UserResource (
                birthDate: Option[CertifiableFieldResourceOfLocalDate] = None,
                email: Option[CertifiableFieldResourceOfstring] = None,
                familyName: Option[CertifiableFieldResourceOfstring] = None,
                    /* User fiscal code */
                fiscalCode: Option[String] = None,
                    /* User internal id */
                id: UUID,
                name: Option[CertifiableFieldResourceOfstring] = None,
                    /* User work contacts */
                workContacts: Option[Map[String, WorkContactResource]] = None
            ) extends ApiModel



