openapi: 3.0.1
info:
  title: pdv-ms-user-registry
  description: User Registry API documentation
  version: "1.0-SNAPSHOT"
tags:
  - name: user
    description: User operations
servers:
  - url: "https://user-registry"
security:
  - apiKeyHeader: [ ]
paths:
  '/users/{id}':
    get:
      tags:
        - user
      summary: Find user
      description: Retrieve the user by its internal id
      operationId: findByIdUsingGET
      parameters:
        - name: id
          description: User internal id
          in: path
          schema:
            type: string
            format: uuid
          style: simple
          required: true
        - name: fl
          description: Field list. Subset of fields to be retrieved for the requested resource
          in: query
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Field"
          style: form
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResource'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
components:
  schemas:
    CertifiableFieldResourceOfLocalDate:
      title: CertifiableFieldResourceOfLocalDate
      required:
        - certification
        - value
      type: object
      properties:
        certification:
          type: string
          description: Certified source of information
          enum:
            - NONE
            - SPID
        value:
          type: string
          description: Field value
          format: date
    CertifiableFieldResourceOfstring:
      title: CertifiableFieldResourceOfstring
      required:
        - certification
        - value
      type: object
      properties:
        certification:
          type: string
          description: Certified source of information
          enum:
            - NONE
            - SPID
        value:
          type: string
          description: Field value
    WorkContactResource:
      title: WorkContactResource
      type: object
      properties:
        email:
          description: User work email
          $ref: "#/components/schemas/CertifiableFieldResourceOfstring"
    UserResource:
      title: UserResource
      required:
        - id
      type: object
      properties:
        birthDate:
          description: User date of birth
          $ref: "#/components/schemas/CertifiableFieldResourceOfLocalDate"
        email:
          description: User email
          $ref: "#/components/schemas/CertifiableFieldResourceOfstring"
        familyName:
          description: User family name
          $ref: "#/components/schemas/CertifiableFieldResourceOfstring"
        fiscalCode:
          type: string
          description: User fiscal code
        id:
          type: string
          description: User internal id
          format: uuid
        name:
          description: User name
          $ref: "#/components/schemas/CertifiableFieldResourceOfstring"
        workContacts:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/WorkContactResource"
          description: User work contacts
    Field:
      type: string
      enum:
        - birthDate
        - email
        - familyName
        - fiscalCode
        - name
        - workContacts
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: x-api-key
      in: header