/**
 * Party Process Micro Service
 * This service is the party process
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.interop.selfcare.partyprocess.client.model

    import java.util.UUID
import it.pagopa.interop.selfcare.partyprocess.client.invoker.ApiModel


            case class Institution (
                id: UUID,
                    /* external institution id */
                externalId: String,
                    /* origin institution id (e.g iPA code) */
                originId: String,
                description: String,
                digitalAddress: String,
                address: String,
                zipCode: String,
                    /* institution tax code */
                taxCode: String,
                    /* The origin form which the institution has been retrieved */
                origin: String,
                    /* institution type */
                institutionType: Option[String] = None,
                attributes: Seq[Attribute]
            ) extends ApiModel



