/**
 * Party Process Micro Service
 * This service is the party process
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.interop.selfcare.partyprocess.client.model

    import java.util.UUID
import it.pagopa.interop.selfcare.partyprocess.client.invoker.ApiModel


            case class OnboardingData (
                id: UUID,
                externalId: String,
                originId: String,
                description: String,
                taxCode: String,
                digitalAddress: String,
                address: String,
                zipCode: String,
                state: RelationshipState,
                role: PartyRole,
                productInfo: ProductInfo,
                    /* institution type */
                institutionType: Option[String] = None,
                    /* pricing plan */
                pricingPlan: Option[String] = None,
                billing: Option[Billing] = None,
                    /* The origin form which the institution has been retrieved */
                origin: String,
                    /* certified attributes bound to this institution */
                attributes: Seq[Attribute]
            ) extends ApiModel



