/**
 * Party Process Micro Service
 * This service is the party process
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.interop.selfcare.partyprocess.client.model

    import java.util.UUID
import it.pagopa.interop.selfcare.partyprocess.client.invoker.ApiModel


            case class OnboardingInfo (
                    /* User internal id */
                userId: Option[UUID] = None,
                institutions: Seq[OnboardingData]
            ) extends ApiModel



