/**
 * Party Process Micro Service
 * This service is the party process
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.interop.selfcare.partyprocess.client.model

import it.pagopa.interop.selfcare.partyprocess.client.invoker.ApiModel


            case class Problem (
                    /* URI reference of type definition */
                `type`: String,
                    /* The HTTP status code generated by the origin server for this occurrence of the problem. */
                status: Int,
                    /* A short, summary of the problem type. Written in english and readable */
                title: String,
                    /* A human readable explanation of the problem. */
                detail: Option[String] = None,
                errors: Seq[ProblemError]
            ) extends ApiModel



