/**
 * Party Process Micro Service
 * This service is the party process
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.interop.selfcare.partyprocess.client.model

import it.pagopa.interop.selfcare.partyprocess.client.invoker.ApiModel


            case class ProductRolesResponse (
                    /* binding between manager and its platform roles */
                managerRoles: Seq[String],
                    /* binding between delegate and its platform roles */
                delegateRoles: Seq[String],
                    /* binding between operator and its platform roles */
                operatorRoles: Seq[String]
            ) extends ApiModel



