/**
 * Party Process Micro Service
 * This service is the party process
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.interop.selfcare.partyprocess.client.model

import it.pagopa.interop.selfcare.partyprocess.client.invoker.ApiModel




            sealed trait ProductState extends ApiModel

            object ProductState {

                    case object PENDING extends ProductState
                    case object ACTIVE extends ProductState

            def fromValue(value: String): Either[Throwable, ProductState] =
            value match {
                    case "PENDING" => Right(PENDING)
                    case "ACTIVE" => Right(ACTIVE)
            case other => Left(new RuntimeException(s"Unable to decode value $other"))
            }
            }

