/**
 * Party Process Micro Service
 * This service is the party process
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.interop.selfcare.partyprocess.client.model

    import java.time.OffsetDateTime
    import java.util.UUID
import it.pagopa.interop.selfcare.partyprocess.client.invoker.ApiModel


            case class RelationshipInfo (
                id: UUID,
                from: UUID,
                to: UUID,
                role: PartyRole,
                product: ProductInfo,
                state: RelationshipState,
                createdAt: Option[OffsetDateTime] = None,
                updatedAt: Option[OffsetDateTime] = None
            ) extends ApiModel



