/**
 * Party Management Micro Service V1
 * This service is the party manager
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.interop.selfcare.partymanagement.client.api

    import it.pagopa.interop.selfcare.partymanagement.client.model.Problem
import it.pagopa.interop.selfcare.partymanagement.client.invoker._
import it.pagopa.interop.selfcare.partymanagement.client.invoker.CollectionFormats._
import it.pagopa.interop.selfcare.partymanagement.client.invoker.ApiKeyLocations._

    object HealthApi {
    def apply(baseUrl: String = "https://party-management") = new HealthApi(baseUrl)
    }


    class HealthApi(baseUrl: String) {
  /**
   *             Return ok
   * 
   * Expected answers:
   *   code 200 : Problem (successful operation)
   * 
   * Available security schemes:
   *   apiKeySelfcare (apiKey)
   * 
   * @param xSelfcareUid 
   */
        def getStatus(
                                                        )
        (xSelfcareUid:String)(implicit apiKeySelfcare:ApiKeyValue): ApiRequest[Problem] =
        ApiRequest[Problem](ApiMethods.GET, baseUrl, "/status", "application/json")
        .withApiKey(apiKeySelfcare, "Ocp-Apim-Subscription-Key", HEADER)
        
        
        
        
        
        .withHeaderParam("x-selfcare-uid", xSelfcareUid)
        .withSuccessResponse[Problem](200)
        



    }

