openapi: 3.0.1
info:
  title: Party Management Micro Service V1
  description: This service is the party manager
  version: v1
tags:
  - name: public
    description: Public endpoints
    externalDocs:
      description: Find out more
      url: http://swagger.io/
  - name: health
    description: Verify service status
    externalDocs:
      description: Find out more
      url: http://swagger.io/
  - name: party
    description: Manipulate party information
    externalDocs:
      description: Find out more
      url: http://swagger.io/
  - name: external
    description: External id endpoints
    externalDocs:
      description: Find out more
      url: http://swagger.io/
security:
  - apiKeySelfcare: [ ]
servers:
  - url: "https://party-management"
paths:
  '/persons/{id}':
    parameters:
      - $ref: '#/components/parameters/SelfcareUID'
      - name: id
        in: path
        schema:
          type: string
          format: uuid
        required: true
        description: Person ID
    get:
      summary: Retrieves Person by ID
      tags:
        - party
      responses:
        '200':
          description: Person
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Person not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
      operationId: getPersonById
      description: 'returns the identified person, if any.'
    head:
      tags:
        - party
      summary: Verify if a Person exists for a given ID
      description: Return ok
      operationId: existsPersonById
      parameters:
        - name: id
          in: path
          description: The ID of the Person to check
          required: true
          schema:
            description: The Person ID.
            type: string
            format: uuid
            example: e72dd279-5f52-4039-afbe-2b7e432c490e
      responses:
        '200':
          description: Person exists
        '404':
          description: Person not found
  /institutions/{id}:
    parameters:
      - $ref: '#/components/parameters/SelfcareUID'
      - name: id
        in: path
        description: The ID of the Institution to check
        required: true
        schema:
          description: to be defined
          type: string
          format: uuid
          example: e72dd279-5f52-4039-afbe-2b7e432c490e
    get:
      summary: Retrieves Institution by ID
      tags:
        - party
      responses:
        '200':
          description: Institution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Institution'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Institution not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
      operationId: getInstitutionById
      description: 'returns the identified institution, if any.'
    head:
      tags:
        - party
      summary: Verify if an institution exists for a given institutionId
      description: Return ok
      operationId: existsInstitutionById
      responses:
        '200':
          description: successful operation
        '404':
          description: Institution not found
  /institutions/{id}/attributes:
    parameters:
      - $ref: '#/components/parameters/SelfcareUID'
      - schema:
          type: string
          format: uuid
          example: e72dd279-5f52-4039-afbe-2b7e432c490e
        name: id
        in: path
        required: true
        description: Institution ID
    get:
      summary: Retrieves attributes
      tags:
        - party
      responses:
        '200':
          description: Party Attributes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Attributes'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Party not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
      operationId: getPartyAttributes
      description: 'returns the attributes of the identified party, if any.'
  /external/institutions/{externalId}:
    parameters:
      - $ref: '#/components/parameters/SelfcareUID'
      - schema:
          type: string
        name: externalId
        in: path
        required: true
        description: External Institution ID
    get:
      summary: Retrieves Institution by ID
      tags:
        - external
      responses:
        '200':
          description: Institution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Institution'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Institution not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
      operationId: getInstitutionByExternalId
      description: 'returns the identified institution, if any.'
  /relationships:
    get:
      parameters:
        - $ref: '#/components/parameters/SelfcareUID'
        - in: query
          name: from
          schema:
            type: string
            format: uuid
        - in: query
          name: to
          schema:
            type: string
            format: uuid
        - in: query
          name: roles
          description: comma separated sequence of role to filter the response with
          schema:
            type: array
            items:
              $ref: '#/components/schemas/PartyRole'
            default: [ ]
          explode: false
        - in: query
          name: states
          description: comma separated sequence of states to filter the response with
          schema:
            type: array
            items:
              $ref: '#/components/schemas/RelationshipState'
            default: [ ]
          explode: false
        - in: query
          name: products
          description: comma separated sequence of products to filter the response with
          schema:
            type: array
            items:
              type: string
            default: [ ]
          explode: false
        - in: query
          name: productRoles
          description: comma separated sequence of product roles to filter the response with
          schema:
            type: array
            items:
              type: string
            default: [ ]
          explode: false
      tags:
        - party
      summary: Return a list of relationships
      description: Return ok
      operationId: getRelationships
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Relationships'
        '400':
          description: Invalid ID supplied
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /relationships/{relationshipId}:
    get:
      parameters:
        - $ref: '#/components/parameters/SelfcareUID'
        - name: relationshipId
          in: path
          description: The ID of the Relationship to retrieve
          required: true
          schema:
            type: string
            format: uuid
      tags:
        - party
      summary: Retrieve the relationship for the given relationshipId
      description: Return relationship
      operationId: getRelationshipById
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Relationship'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Relationship not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /bulk/institutions:
    parameters:
      - $ref: '#/components/parameters/SelfcareUID'
    post:
      summary: Retrieves a collection of institutions
      tags:
        - party
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkPartiesSeed'
      responses:
        '200':
          description: collection of institutions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BulkInstitutions'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Institutions not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
      operationId: bulkInstitutions
      description: 'returns a collection of all the parties for the corresponding identifiers.'
  /status:
    get:
      parameters:
        - $ref: '#/components/parameters/SelfcareUID'
      tags:
        - health
      summary: Health status endpoint
      description: Return ok
      operationId: getStatus
      responses:
        '200':
          description: successful operation
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
components:
  parameters:
    SelfcareUID:
      in: header
      name: x-selfcare-uid
      required: true
      schema:
        type: string
  schemas:
    Person:
      required:
        - id
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 97c0f418-bcb3-48d4-825a-fe8b29ae68e5
      additionalProperties: false
    Institution:
      required:
        - id
        - externalId
        - originId
        - description
        - digitalAddress
        - address
        - zipCode
        - taxCode
        - attributes
        - origin
        - institutionType
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 97c0f418-bcb3-48d4-825a-fe8b29ae68e5
        externalId:
          type: string
          description: external institution id
          example: c_f205
        originId:
          type: string
          description: origin institution id (e.g iPA code)
          example: c_f205
        description:
          type: string
          example: AGENCY X
        digitalAddress:
          type: string
          format: email
          example: email@pec.mail.org
        address:
          type: string
          example: via del campo
        zipCode:
          type: string
          example: '20100'
        taxCode:
          type: string
          description: institution tax code
        origin:
          type: string
          description: The origin form which the institution has been retrieved
          example: IPA
        institutionType:
          type: string
          description: institution type
          example: PA
        attributes:
          $ref: '#/components/schemas/Attributes'
      additionalProperties: false
    PartyRole:
      enum:
        - MANAGER
        - DELEGATE
        - SUB_DELEGATE
        - OPERATOR
      type: string
      description: Represents the generic available role types for the relationship
    RelationshipState:
      enum:
        - PENDING
        - ACTIVE
        - SUSPENDED
        - DELETED
        - REJECTED
      type: string
      description: Represents the party relationship state
    Attributes:
      type: array
      items:
        $ref: '#/components/schemas/Attribute'
    Attribute:
      required:
        - origin
        - code
        - description
      type: object
      properties:
        origin:
          type: string
          description: 'origin of the certified attribute, e.g.: IPA'
        code:
          type: string
          description: 'original identifier as defined at origin side, e.g.: IPA attribute code'
        description:
          type: string
          description: human readable description of the attribute
      additionalProperties: false
    RelationshipProduct:
      required:
        - id
        - role
        - createdAt
      type: object
      properties:
        id:
          type: string
        role:
          type: string
        createdAt:
          type: string
          format: date-time
    Relationship:
      required:
        - id
        - from
        - to
        - role
        - product
        - state
      type: object
      properties:
        id:
          type: string
          format: uuid
        from:
          type: string
          description: person ID
          format: uuid
        to:
          type: string
          description: institution ID
          format: uuid
        filePath:
          type: string
          description: path of the file containing the signed onboarding document
        fileName:
          type: string
          description: name of the file containing the signed onboarding document
        contentType:
          type: string
          description: content type of the file containing the signed onboarding document
        tokenId:
          type: string
          description: confirmation token identifier
          format: uuid
        role:
          $ref: '#/components/schemas/PartyRole'
        product:
          $ref: '#/components/schemas/RelationshipProduct'
        state:
          $ref: '#/components/schemas/RelationshipState'
        pricingPlan:
          type: string
          description: pricing plan
        institutionUpdate:
          $ref: '#/components/schemas/InstitutionUpdate'
        billing:
          $ref: '#/components/schemas/Billing'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      additionalProperties: false
    Relationships:
      required:
        - items
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Relationship'
      additionalProperties: false
    Problem:
      required:
        - type
        - status
        - title
        - errors
      properties:
        type:
          type: string
          description: URI reference of type definition
        status:
          maximum: 600.0
          exclusiveMaximum: true
          minimum: 100.0
          type: integer
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          format: int32
          example: 503
        title:
          maxLength: 64
          pattern: '^[ -~]{0,64}$'
          type: string
          description: 'A short, summary of the problem type. Written in english and readable'
          example: Service Unavailable
        detail:
          maxLength: 4096
          pattern: '^.{0,1024}$'
          type: string
          description: A human readable explanation of the problem.
          example: Request took too long to complete.
        errors:
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/ProblemError'
      additionalProperties: false
    ProblemError:
      required:
        - code
        - detail
      properties:
        code:
          maxLength: 8
          minLength: 8
          pattern: '^[0-9]{3}-[0-9]{4}$'
          type: string
          description: Internal code of the error
          example: 123-4567
        detail:
          maxLength: 4096
          pattern: '^.{0,1024}$'
          type: string
          description: A human readable explanation specific to this occurrence of the problem.
          example: Parameter not valid
    InstitutionUpdate:
      type: object
      properties:
        institutionType:
          type: string
          description: The type of the institution
          example: PA
        description:
          type: string
          example: AGENCY X
        digitalAddress:
          type: string
          format: email
          example: email@pec.mail.org
        address:
          type: string
          example: via del campo
        taxCode:
          type: string
          description: institution tax code
    Billing:
      required:
        - vatNumber
        - recipientCode
      type: object
      properties:
        vatNumber:
          type: string
          description: institution vat number
        recipientCode:
          type: string
          description: institution recipient code
        publicServices:
          type: boolean
          description: institution recipient code
      additionalProperties: false
    BulkInstitutions:
      type: object
      required:
        - found
        - notFound
      properties:
        found:
          type: array
          description: the collection of institutions found.
          items:
            $ref: '#/components/schemas/Institution'
        notFound:
          type: array
          items:
            type: string
          description: the identifiers of institutions not found.
    BulkPartiesSeed:
      type: object
      required:
        - partyIdentifiers
      properties:
        partyIdentifiers:
          type: array
          items:
            type: string
            format: uuid
          description: the identifiers of party
  securitySchemes:
    apiKeySelfcare:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
